export default {
  MOVIES: 'MOVIES',
  CURRENT_PAGE: 'CURRENT_PAGE',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  REMOVE_MOVIE: 'REMOVE_MOVIE',
  SEARCH_TOGGLE: 'SEARCH_TOGGLE',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
};
